name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
      
    - name: Log into Docker Hub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login  --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/quotedaily-streamlit-cicd-pipeline:v1 .
      
    - name: Log into Docker Hub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login jpacerqueira83.docker.com --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name : Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/quotedaily-streamlit-cicd-pipeline:v1
      
